name: Audit

on:
  pull_request:
    paths:
      - '**/*.go'
  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'

      - name: Install Dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

  tests:
    runs-on: ubuntu-latest
    needs:
      - linters
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'

      - name: Install Dependencies
        run: go mod download

      - name: Install junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Run Tests
        run: go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report.xml
          path: report.xml
